Measure PQ192-HH
CMSgov/cms-mdct-qmr pull request #1019
Opened 2022-05-06 13:38 UTC by abelzer212

## Purpose

Bring in new measure PQ192-HH

#### Linked Issues to Close

https://qmacbis.atlassian.net/browse/OY2-9906

#### Pull Request Creator Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [x] This PR meets all acceptance criteria for those issues.
- [x] This PR and linked issue(s) are adequately documented
- [x] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [x] Someone has been assigned this PR.
- [x] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-05-06 14:40 UTC, jdinh8124 approved these changes
Looks good to me

2022-05-06 15:32 UTC, jphechter requested changes
Needs one change, otherwise LGTM 👍

2022-05-06 15:32 UTC, jphechter commented on services/ui-src/src/measures/2021/PQI92HH/index.tsx
> +            />
Missing `calcTotal`

2022-05-09 13:32 UTC, abelzer212 commented on services/ui-src/src/measures/2021/PQI92HH/index.tsx
> +            />
Just added that back in

2022-05-09 13:59 UTC, jphechter submitted a review, later dismissed
LGTM 👍

2022-05-11 18:21 UTC, merged