Oy2 12731
CMSgov/cms-mdct-qmr pull request #1028
Opened 2022-05-09 13:37 UTC by charmcitygavin

## Purpose

This PR adds the ability for the user to add state-specific measures to Health Homes core sets.

#### Linked Issues to Close

_Links to issue(s) that are closed by this PR. Be sure to use the phrase "Closes #XXX" for each issue, so they automatically close_

## Approach

_How does this change address the issue?_

## Learning

_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Assorted Notes/Considerations

_List any other information that you think is important... a post-merge activity, someone to notify, etc._

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-05-24 18:32 UTC, abelzer212 submitted a review, later dismissed

2022-06-06 15:16 UTC, benjaminpaige commented on services/ui-src/src/components/AddSSM/index.tsx
> +                isRequired={true}
lets change this to rules={{ required: true}} and get rid of the isRequired prop for textInput and textArea

2022-06-06 15:16 UTC, benjaminpaige commented on services/ui-src/src/components/AddSSM/index.tsx
> +                isRequired={true}
rules={{ required: true}}

2022-06-06 15:17 UTC, benjaminpaige commented on services/ui-src/src/components/Inputs/TextArea/index.tsx
> +  isRequired = false,
dont need this

2022-06-06 15:18 UTC, benjaminpaige commented on services/ui-src/src/components/Inputs/TextArea/index.tsx
> +        isRequired={isRequired}
remove

2022-06-06 15:18 UTC, benjaminpaige commented on services/ui-src/src/components/Inputs/TextInput/index.tsx
> +  isRequired?: boolean;
we can remove all of the isRequired from this comp

2022-06-06 16:04 UTC, benjaminpaige commented on services/ui-src/src/views/Qualifiers/Common/audit.tsx
> +            item?.measure?.includes("SS-") && item?.measure?.includes("-HH")
you could prob also just check for item?.measure?.userCreated

2022-06-06 16:06 UTC, benjaminpaige requested changes
just a few suggestions. let me know if you have any questions

2022-06-06 17:52 UTC, charmcitygavin commented on services/ui-src/src/views/Qualifiers/Common/audit.tsx
> +            item?.measure?.includes("SS-") && item?.measure?.includes("-HH")
Great catch! I think I wrote this part way back when the `userCreated` attribute didn't exist yet 🙃

2022-06-06 18:10 UTC, charmcitygavin commented on services/ui-src/src/components/Inputs/TextArea/index.tsx
>    isRequired?: boolean;
@benjaminpaige Looks like a few common question components use the `name` property so I'll leave it in.

But it doesn't look like we're using the `placeholder` property anywhere with the TextArea component, so I'll remove it. 👍🏻

2022-06-06 18:18 UTC, charmcitygavin commented on services/ui-src/src/components/Inputs/TextArea/index.tsx
> +        isRequired={isRequired}
I'll leave `as={ResizeTextarea}` in to ensure the text area grows automatically as the user types. As for `data-cy`, I'm not sure how many Cypress tests rely on this (it's been a part of the component for at least the last 4 months), and other input components also include it, so I think it might be a good idea to leave it in for now to prevent broken tests and keep things consistent.

2022-06-06 18:19 UTC, charmcitygavin commented on services/ui-src/src/components/Inputs/TextArea/index.tsx
> -  maxLength?: number;
Turns out we don't need this anymore since the character count limit has been removed.

2022-06-06 18:20 UTC, charmcitygavin commented on services/ui-src/src/components/Inputs/TextInput/index.tsx
> +  isRequired?: boolean;
👍🏻

2022-06-06 18:21 UTC, charmcitygavin commented on services/ui-src/src/components/Inputs/TextArea/index.tsx
> +  isRequired = false,
👍🏻

2022-06-06 18:21 UTC, charmcitygavin commented on services/ui-src/src/components/AddSSM/index.tsx
> +                isRequired={true}
👍🏻

2022-06-06 18:21 UTC, charmcitygavin commented on services/ui-src/src/components/AddSSM/index.tsx
> +                isRequired={true}
👍🏻

2022-06-06 18:39 UTC, benjaminpaige submitted a review, later dismissed
looks great! this gonna be so awesome!

2022-06-08 15:20 UTC, abelzer212 approved these changes

2022-06-08 15:21 UTC, merged