Delete Client Certs when destroying branch
CMSgov/cms-mdct-qmr pull request #1126
Opened 2022-05-19 19:53 UTC by gitsierra

## Purpose

https://qmacbis.atlassian.net/browse/OY2-18073

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-05-20 17:42 UTC, abelzer212 approved these changes

2022-05-20 17:43 UTC, abelzer212 requested changes

2022-05-20 17:43 UTC, abelzer212 commented on destroy.sh
> +  sleep 10
This should probably be more like 10,000, or 20,0000, 10 milliseconds isn't really enough time for anything to happen

2022-05-20 19:03 UTC, gitsierra commented on destroy.sh
> +  sleep 10
Sleep in bash defaults to seconds

2022-05-21 02:00 UTC, abelzer212 approved these changes

2022-05-21 02:00 UTC, merged