Add AAB-AD
CMSgov/cms-mdct-qmr pull request #1283
Opened 2022-06-09 18:39 UTC by abelzer212

## Purpose

Added AAB-AD 2022 Measure

#### Linked Issues to Close

https://qmacbis.atlassian.net/browse/OY2-17989

## Approach

I had to add a new rate component because the math is completely different. In the process I refactored a few naming conventions. 

#### Pull Request Creator Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [x] This PR meets all acceptance criteria for those issues.
- [x] This PR and linked issue(s) are adequately documented
- [x] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [x] Someone has been assigned this PR.
- [x] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-06-09 19:11 UTC, jdinh8124 submitted a review, later dismissed
Looks good to me, appreciate the few areas of improvement

2022-06-09 19:11 UTC, jdinh8124 commented on services/ui-src/src/measures/2022/CommonQuestions/DefinitionsOfPopulation/index.tsx
> +                        </CUI.Text>,
I'm guessing we missed this before, thanks for catching this

2022-06-09 19:11 UTC, jdinh8124 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/context.ts
> +export type ComponentFlagType = "DEFAULT" | "IU" | "PCR" | "AAB";
Appreciate the clarity of naming

2022-06-09 19:11 UTC, jdinh8124 commented on services/ui-src/src/measures/2022/CommonQuestions/PerformanceMeasure/data.ts
> +  customPrompt?: string; // Default: "Enter a number for the numerator and the denominator. Rate will auto-calculate:"
Nice

2022-06-09 19:11 UTC, jdinh8124 commented on services/ui-src/src/measures/2022/index.tsx
>  const twentyTwentyOneMeasures = {
I'll fix the variable name here on a separate PR

2022-06-10 01:13 UTC, jphechter requested changes
The biggest thing for me is questions around the validation. Would like to talk about reworking Rate to accommodate this measure's needs. It just creates yet another component and complexity in OMS.

Overall, changes look good.

2022-06-10 01:13 UTC, jphechter commented on services/ui-src/src/measures/2022/CommonQuestions/PerformanceMeasure/data.ts
> +  customPrompt?: string; // Default: "Enter a number for the numerator and the denominator. Rate will auto-calculate:"
☝️

2022-06-10 01:13 UTC, jphechter commented on services/ui-src/src/measures/2022/index.tsx
>  const twentyTwentyOneMeasures = {
I have this in the FUA-CH PR. Left a comment in the code asking if this was intentional.

2022-06-10 01:13 UTC, jphechter commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> +      break;
Love a good alphabetized list

2022-06-10 01:13 UTC, jphechter commented on services/ui-src/src/components/AABRate/index.tsx
> +  };
Looking at the added complexity to OMS, I'm more in favor of working this into the alternate rate formula into the regular Rate component.

2022-06-10 13:54 UTC, abelzer212 commented on services/ui-src/src/measures/2022/AABAD/validation.ts
> +
Yeah, that was intentional because it's an inverse, I need to sit down with Dany today to see what the ask for validation is on this particular measure

2022-06-10 13:57 UTC, abelzer212 commented on services/ui-src/src/components/AABRate/index.tsx
> +  };
To your point about adding an alternate rate, I think that would be good if we had another use case for it in 2022, but right everything else is just using the regular formula * some factor of 10. If another story comes up with that need we should revisit it then, but the rate component touches so much that I don't want to change it too drastically this late in the game without a really good reason.

2022-06-10 14:09 UTC, jphechter commented on services/ui-src/src/components/AABRate/index.tsx
> +  };
As lead, I'll defer to your opinion, but given that we have quite a few tests around Rate this kind of change doesn't give me much pause. I think if anything it makes the other components more secure and reduces overall complexity.

2022-06-17 16:22 UTC, benjaminpaige reviewed
a lot going on in that new rate comp and the one-off handling in oms. That being the case Im gonna ask @daniel-belcher to take a look as he may be better able to provide feedback on this implementation.

2022-06-17 16:43 UTC, benjaminpaige commented
this is really great, but let's not merge this until we go over it together, there may be some ways we can update the rate calc functions to make the rate comp more scalable for these one-off situations.

2022-06-22 14:53 UTC, closed without merging