read me update
CMSgov/cms-mdct-qmr pull request #1290
Opened 2022-06-10 18:10 UTC by gitsierra

## Purpose

Update readme with details on how to manually destroy resources from the terminal 

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-06-10 18:15 UTC, 13bfrancis approved these changes

2022-06-10 18:19 UTC, abelzer212 requested changes

2022-06-10 18:19 UTC, abelzer212 commented on README.md
> +## Destroy
Maybe change to "Local Destroy Instructions"

2022-06-10 18:19 UTC, abelzer212 commented on README.md
> +Want to destroy from your Mac? This may be necessary in some cases where you have orphaned infrastructure
Not everyone will be on a mac

2022-06-10 18:19 UTC, abelzer212 commented on README.md
> +- Install/configure the AWS CLI (You will have to copy AWS keys into your terminal)
I'd expand this out to talk about the steps to retrieve those credentials from the cloudtamer site

2022-06-10 18:19 UTC, abelzer212 commented on README.md
> +- brew install jq (if you don't have already installed)
What is jq? why are we installing it (some brief description will help give context)

2022-06-10 18:19 UTC, abelzer212 commented on README.md
> +- sh destroy.sh "name_of_your_branch" and re-enter the branch name once it has found all associated resources
Are there any troubleshooting things to try if this command fails?

2022-06-10 20:17 UTC, jphechter requested changes

2022-06-10 20:17 UTC, jphechter commented on README.md
> +## Local Destroy Instructions
Can we change this slightly? To me "Local Destroy Instructions" sounds like it refers to something in my local environment. 

I don't have a perfect alternative, but maybe something like this?
- Destroy Orphaned AWS Infrastructure
- Destroy Infrastructure from Command Line

2022-06-10 20:17 UTC, jphechter commented on README.md
> +- Go to the mdct-qmr-dev project and click on "Cloud access", click on your account, click on mdctqmr-developer-admin, click on Short-term Access Keys, Then paste the the text from Option 1 into your
I think these could be individual bullets

2022-06-10 20:17 UTC, jphechter commented on README.md
> +- brew install jq (if you don't have already installed) (jq is command-line JSON processor necessary for the destroy script to run properly)
```suggestion
- `brew install jq` Install jq (command-line JSON processor). This is necessary for the destroy script to run properly.
```

2022-06-10 20:17 UTC, jphechter commented on README.md
> +- sh destroy.sh "name_of_your_branch" and re-enter the branch name once it has found all associated resources. (There shouldn't be any errors but if there are any. Re-running the script should fix it
```suggestion
- `sh destroy.sh name_of_your_branch` Run destroy script. You will be prompted to re-enter the branch name once it has found all associated resources. (There shouldn't be any errors but if there are any. Re-running the script should fix it)
```

2022-06-13 17:43 UTC, jphechter approved these changes
Love it! 👍

2022-06-15 14:09 UTC, benjaminpaige approved these changes

2022-06-16 17:57 UTC, abelzer212 approved these changes

2022-06-16 18:30 UTC, merged