OY017992: FFY2022 FUMCH Measure
CMSgov/cms-mdct-qmr pull request #1301
Opened 2022-06-14 15:35 UTC by karla-vm

## Purpose

Adding FUM-CH measure, closes [OY-17992](https://qmacbis.atlassian.net/browse/OY2-17992). 

Application endpoint: [Quality Measure Reporting](https://d1nz3gmcjkjs1v.cloudfront.net/).

#### Linked Issues to Close

Closes OY-17992.

## Approach

Created a new measure.

## Learning

How to create a new measure, how to differentiate between Child, Adult, and Health Home measures in the code.

## Assorted Notes/Considerations

N/A

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-06-14 15:39 UTC, abelzer212 approved these changes

2022-06-14 15:59 UTC, jphechter requested changes
There are a couple imports that need updating, but everything else looks good to me!

2022-06-14 15:59 UTC, jphechter commented on services/ui-src/src/measures/2022/FUMCH/types.ts
> +import * as Types from "measures/2021/CommonQuestions/types";
```suggestion
import * as Types from "measures/2022/CommonQuestions/types";
```

2022-06-14 15:59 UTC, jphechter commented on services/ui-src/src/measures/2022/FUMCH/index.tsx
> +import * as CMQ from "measures/2021/CommonQuestions";
```suggestion
import * as CMQ from "measures/2022/CommonQuestions";
```
HEDIS options are incorrect. Should be as simple as updating this import.

current:
![Screen Shot 2022-06-14 at 11 49 20 AM](https://user-images.githubusercontent.com/22647707/173620946-a8d24773-02eb-4766-957e-9b533e996846.png)

expected:
![Screen Shot 2022-06-14 at 11 50 51 AM](https://user-images.githubusercontent.com/22647707/173621166-268569c3-8200-4cc7-ae9a-026c26ef7951.png)

2022-06-14 15:59 UTC, jphechter commented on services/ui-src/src/measures/2022/FUMCH/validation.ts
> +import * as GV from "measures/2021/globalValidations";
```suggestion
import * as GV from "measures/2022/globalValidations";
```

2022-06-14 15:59 UTC, jphechter commented on services/ui-src/src/measures/2022/FUMCH/validation.ts
> +    ...errorArray,
```suggestion
```
Tiny nit, but if you can get to this point `errorArray` won't have a value. You'd be spreading an empty array. If `errorArray` has a value it would be returned on 23.

2022-06-14 15:59 UTC, jphechter commented on services/ui-src/src/measures/2022/FUMCH/data.ts
> +import { DataDrivenTypes } from "measures/2021/CommonQuestions/types";
```suggestion
import { DataDrivenTypes } from "measures/2022/CommonQuestions/types";
```

2022-06-14 15:59 UTC, jphechter commented on services/ui-src/src/measures/2022/FUMCH/index.tsx
> +import { getPerfMeasureRateArray } from "measures/2021/globalValidations";
```suggestion
import { getPerfMeasureRateArray } from "measures/2022/globalValidations";
```

2022-06-14 15:59 UTC, jphechter commented on services/ui-src/src/measures/2022/FUMCH/validation.ts
> +import { OMSData } from "measures/2021/CommonQuestions/OptionalMeasureStrat/data";
```suggestion
import { OMSData } from "measures/2022/CommonQuestions/OptionalMeasureStrat/data";
```

2022-06-14 17:33 UTC, jphechter approved these changes
LGTM 👍 

Great 1st PR on the repo!

2022-06-16 15:40 UTC, abelzer212 approved these changes

2022-06-16 15:48 UTC, merged