Add spa Ids per year
CMSgov/cms-mdct-qmr pull request #1340
Opened 2022-06-23 20:08 UTC by gitsierra

## Purpose

https://qmacbis.atlassian.net/browse/OY2-18183

Application endpoint:  https://d2rdivmid9my71.cloudfront.net/

Add Health Home Spa Ids per Year

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-06-23 20:44 UTC, jphechter requested changes
Looks good overall. Not even gonna pretend that I actually read through the SPA docs on the ticket. Would like to use the `SPAi` type instead of `any`.

2022-06-23 20:44 UTC, jphechter commented on services/ui-src/src/libs/spaLib.ts
> +export const SPA: any = {
```suggestion
export const SPA: {[year: string]: SPAi[]} = {
```
In the interest of using the SPAi type, could we do this?

2022-06-23 20:44 UTC, jphechter commented on services/ui-src/src/views/StateHome/index.tsx
> +  const spaIds = filteredSpas.map((s: any) => s.id);
```suggestion
  const filteredSpas = SPA[year!].filter((s: SPAi) => s.state === state);
  const spaIds = filteredSpas.map((s: SPAi) => s.id);
```
In all of the instances where we're applying `any`, could we use the SPAi type? If we specify the type in `spaLib.ts` we may actually to just remove the type.

2022-06-23 20:44 UTC, jphechter commented on services/ui-src/src/views/StateHome/index.tsx
> +    spaIds.every((s: any) =>
same as above

2022-06-23 20:44 UTC, jphechter commented on services/ui-src/src/views/CoreSet/index.tsx
> +          (s: any) => s.id === coreSetInfo[1] && s.state === state
same as in `StateHome/index.tsx`

2022-06-23 20:44 UTC, jphechter commented on services/ui-src/src/views/CoreSet/index.tsx
> +          (s: any) => s.id === coreSet[1] && s.state === state
same as in `StateHome/index.tsx`

2022-06-23 20:44 UTC, jphechter commented on services/ui-src/src/views/AddHHCoreSet/index.tsx
> +    .sort((a: any, b: any) => (a.displayValue > b.displayValue && 1) || -1);
same as in `StateHome/index.tsx`

2022-06-24 14:09 UTC, benjaminpaige commented on services/ui-src/src/libs/spaLib.ts
> +    { id: "20-0002", state: "CA", name: "California Behavioral Health Home" },
is there a reason we didn't do: 

"2021": {
CA: [
{id: "19-0037", name: "California Health Home Program (HHP)"},
{id: "20-0002", name: "California Behavioral Health Home" }
], ...

2022-06-24 15:00 UTC, benjaminpaige submitted a review, later dismissed

2022-06-24 19:17 UTC, jphechter submitted a review, later dismissed
LGTM 👍

2022-06-28 16:56 UTC, benjaminpaige approved these changes

2022-06-28 16:57 UTC, merged