OY2-18870: Replicate Health Home Measures for FFY 2022
CMSgov/cms-mdct-qmr pull request #1341
Opened 2022-06-24 12:31 UTC by karla-vm

## Purpose

The 2021 Health Home measures are being replicated and made available for FFY 2022. Users should be able to go in and report on 2022 HH core sets.

Application endpoint:  https://dgmeuzoy53oeq.cloudfront.net/

#### Linked Issues to Close

Closes [OY2-18870](https://qmacbis.atlassian.net/browse/OY2-18870).

## Approach

Replicating the 2021 Health Home measures for FFY 2022 allows users to report on that fiscal year.

## Learning

For this change, I paired with @abelzer212 to understand the changes required from 2021 to 2022.

## Assorted Notes/Considerations

N/A

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-06-24 14:29 UTC, abelzer212 requested changes

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/MeasurementSpecification/index.tsx
> -          },
This needs to be left in

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/MeasurementSpecification/index.tsx
> +          },
This needs to be removed

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -    rateCalculation,
I believe this needs to be left in

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -        rateCalc={rateCalculation}
Same with this one

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -    rateCalculation,
This also needs to stay

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -              rateCalc={rateCalculation}
This needs to stay too

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -    rateCalculation,
Also needs to stay

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -          rateCalc={rateCalculation}
This needs to stay too

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -            {customPrompt ??
This also needs to stay, and the revision needs to not be there

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -  const { categories, qualifiers, calcTotal, customPrompt } =
Custom prompt needs to stay here

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -    rateCalculation,
Rate Calculation and custom prompt should stay

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -            {customPrompt ??
Custom Prompt needs to stay

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -      const RateComponent = (
I don't think this should be removed but check with @daniel-belcher on that

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -          RateComponent,
This is where the custom rate component is brought in

2022-06-24 14:29 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -    case "AAB":
The AAB Case should stay I believe

2022-06-24 14:35 UTC, abelzer212 commented on services/ui-src/src/measures/2022/CommonQuestions/types.ts
> -  | typeof DC.HEDIS_MY_2021
This should stay and the revision should not be done

2022-06-24 15:06 UTC, jphechter requested changes
I think there are some changes in here that we don't actually want to include. Let me know if we need to talk through anything.

2022-06-24 15:06 UTC, jphechter commented on services/ui-src/src/measures/2022/globalValidations/validateNoNonZeroNumOrDenom/index.ts
> +export const _validationRateNotZero = ({ location, rateData }: UVFP) => {
Is there a reason we're exporting this? The design pattern in our globalValidation functions is to have private `_validation` functions that do the actual validation check. They should be invoked by a specific PM or OMS function. This function `_validationRateNotZero` should never be called outside this file.
```suggestion
const _validationRateNotZero = ({ location, rateData }: UVFP) => {
```

2022-06-24 15:06 UTC, jphechter commented on services/ui-src/src/measures/2022/globalValidations/validateNoNonZeroNumOrDenom/index.ts
> +}: ValProps) => {
Same as above.
```suggestion
const _validationRateZero = ({
  location,
  rateData,
  hybridData,
}: ValProps) => {
```

2022-06-24 15:07 UTC, jphechter commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> -    case "AAB":
AAB-AD does not have it's own componentFlag, so this should actually be safe to remove.

2022-06-27 16:13 UTC, abelzer212 approved these changes

2022-06-27 17:28 UTC, jphechter approved these changes

2022-06-27 17:28 UTC, jphechter commented on services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
> +            auto-calculate`}
Total nit, but do we need to keep this colon?
```suggestion
            auto-calculate:`}
```

2022-06-28 14:41 UTC, benjaminpaige commented
just the failing cypress tests to resolve. stemming from this assertion failure `AssertionError: Timed out retrying after 15000ms: expected '<button.chakra-button.css-1yhq6yr>' to be 'disabled'`

prob a classname issue

2022-06-28 20:48 UTC, benjaminpaige approved these changes

2022-07-06 14:31 UTC, merged