Oy2 19014 2
CMSgov/cms-mdct-qmr pull request #1425
Opened 2022-07-26 14:38 UTC by gitsierra

## Purpose

_Describe the problem or feature in addition to a link to the issues._

#### Linked Issues to Close

_Links to issue(s) that are closed by this PR. Be sure to use the phrase "Closes #XXX" for each issue, so they automatically close_

## Approach

_How does this change address the issue?_

## Learning

_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Assorted Notes/Considerations

_List any other information that you think is important... a post-merge activity, someone to notify, etc._

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-07-29 15:26 UTC, TheDanMiller requested changes

2022-08-02 10:46 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/AMMAD/index.test.tsx
> +  it("should not pass a11y tests", async () => {
Not sure we need this test -- in this test if I am following we are verifying ally works and thats not on us

thoughts?

2022-08-02 10:50 UTC, TheDanMiller submitted a review, later dismissed
@gitsierra please ticket the moving of the read only test to somewhere more appropriate. It does not need done for each measure.

Did we ticket the fileupload and 409 tests somewhere else

2022-08-02 10:50 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/AMMAD/index.test.tsx
> +  it("should not allow non state users to edit forms by disabling buttons", async () => {
is this controlled at the measure level or somewhere else. If this code is the same for all measures then we should test it once where that logic happens if that makes sense. We can test it on the AMMAD measure at that level

2022-08-02 13:09 UTC, abelzer212 commented on services/ui-src/src/measures/2022/AMMAD/index.test.tsx
> +  it("should not pass a11y tests", async () => {
I don't think it's on us to make sure Ally works, but from testing I like making sure that we can make a test fail, and I'm not sure how else we would do that with our tests.

2022-08-02 13:16 UTC, abelzer212 commented on services/ui-src/src/measures/2022/AMMAD/index.test.tsx
> +  it("should not pass a11y tests", async () => {
I just pulled that one out

2022-08-02 14:36 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/AMMAD/index.test.tsx
> +  it("should not allow non state users to edit forms by disabling buttons", async () => {
The only thing I will say to that is testing it here is great but it makes that other part show up uncovered in reporting. 
@abelzer212

2022-08-02 16:19 UTC, merged