Mscad fix
CMSgov/cms-mdct-qmr pull request #1459
Opened 2022-08-05 17:40 UTC by nnti

## Purpose

Fixed data source selection validation issue.

#### Linked Issues to Close

https://qmacbis.atlassian.net/browse/MDCT-491

## Approach

Validation error message is not displayed when a data source selection is made.

## Learning

N/A

## Assorted Notes/Considerations

N/A

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-08-05 17:56 UTC, abelzer212 requested changes

2022-08-05 17:56 UTC, abelzer212 commented on services/ui-src/src/measures/2021/globalValidations/validateAtLeastOneDataSource/index.ts
> +  console.log("error message: ", errorMessage);
Remove these console logs

2022-08-05 17:56 UTC, abelzer212 commented on yarn.lock
>      traverse "^0.6.6"
With all of these yarn lock changes can you make sure that one other person can still run the project? Occasionally yarn lock changes will mess up local development

2022-08-08 15:18 UTC, gmrabian commented on package.json
> +    "dynamodb": "^1.3.0"
Since all the other dependencies are in devDependencies I wonder if it's worth putting these there too. I see `cypress-image-snapshot` was already here but I'd guess it doesn't need to be. I'm also not totally sure the difference so let me know!

2022-08-08 15:40 UTC, nnti commented on package.json
> +    "dynamodb": "^1.3.0"
It's not required. I've removed the dynamodb dependency. @gmrabian

2022-08-08 15:45 UTC, nnti commented on package.json
> +    "dynamodb": "^1.3.0"
I don't think I added the cypress-image-snapshot dependency. I didn't use it for this PR but I'm not if it's being used somewhere else @gmrabian

2022-08-08 15:49 UTC, gmrabian commented on package.json
> +    "dynamodb": "^1.3.0"
Good stuff. Thanks!

2022-08-08 15:53 UTC, gmrabian approved these changes
Confirmed locally! 
Btw you can remove the yarn.lock changes now since there are no package updates.

2022-08-08 16:21 UTC, gmrabian submitted a review, later dismissed
Clean!

2022-08-08 16:23 UTC, nnti commented on yarn.lock
>      traverse "^0.6.6"
No changes in yarn lock. I've revert yarn lock to has it was in the main branch. @abelzer212

2022-08-08 18:26 UTC, abelzer212 approved these changes

2022-08-11 15:08 UTC, karla-vm approved these changes

2022-08-11 15:10 UTC, TheDanMiller approved these changes

2022-08-12 15:19 UTC, merged