Payload Change for Mathematica
CMSgov/cms-mdct-qmr pull request #1475
Opened 2022-08-19 15:57 UTC by gitsierra

## Purpose

https://qmacbis.atlassian.net/browse/MDCT-1862

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-08-22 13:32 UTC, TheDanMiller commented on services/ui-src/src/components/Rate/index.tsx
>        }
@gitsierra I think we should make these changes in the rateLabel files as well versus mapping. Lets chat about it at standup.

cc: @abelzer212 @karla-vm

2022-08-23 15:33 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/CommonQuestions/DeviationFromMeasureSpecification/index.tsx
>    // if there are no labels then there is no need for the additional checkbox
Same comments as above about if this impacts what is displayed to the user we want to use the text property

2022-08-23 15:33 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/globalValidations/ComplexValidations/ComplexValidateNDRTotals/index.tsx
>              }`,
I think to should be field.text if that is a thing here. Could be I am misreading it

2022-08-23 15:34 UTC, TheDanMiller commented on services/ui-src/src/utils/getLabelText.tsx
> +  acc[data.mathematicaCategory] = data.text;
Should this be using the the text property

2022-08-23 16:32 UTC, abelzer212 commented on services/ui-src/src/measures/2021/globalValidations/validateTotals/index.ts
> +          (categories && categories[idx]) || totalNDR.mathematicaCategory;
This actually needs to be changed back to label because the label this is referencing is a separate label that was being changed

2022-08-24 12:29 UTC, TheDanMiller requested changes
It looks like we are still using incorrect properties at various places in the codebase

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/AMBHH/validation.ts
> +      return pm?.mathematicaCategory === "Age 65 and older";
@gitsierra should this still be testing against mathematicaCategory

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/CDFHH/validation.ts
>      }),
@gitsierra should this be testing against label

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/CommonQuestions/DeviationFromMeasureSpecification/index.tsx
> +          labelText?.[item.mathematicaCategory!] || item.mathematicaCategory,
With the changes in the rateLabel schema this should revert to label? @gitsierra

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/CommonQuestions/PerformanceMeasure/index.tsx
> +          mathematicaId: cat,
why are these mapping from different things? there is a chance that id and category could diverge

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/CommonQuestions/PerformanceMeasure/index.tsx
>    const rates: QMR.IRate[] = qualifiers.map((item, idx) => ({
@gitsierra why are these mapping from the same thing versus coming from different properties?

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/PQI01AD/validation.ts
> +      return pm?.mathematicaCategory === "Age 65 and older";
@gitsierra should this be label

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/PQI05AD/validation.ts
> +      return pm?.mathematicaCategory === "Age 65 and older";
@gitsierra should this be label

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/PQI08AD/validation.ts
> +      return pm?.mathematicaCategory === "Age 65 and older";
@gitsierra should this be label

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2021/PQI92HH/validation.ts
> +      return pm?.mathematicaCategory === "Age 65 and older";
@gitsierra should this be label

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/AMBHH/validation.ts
> +      return pm?.mathematicaCategory === "Age 65 and older";
@gitsierra should this be label

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/CDFHH/validation.ts
> +      return pm?.mathematicaCategory === "Age 65 and older";
@gitsierra should this be label

2022-08-24 12:29 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/CommonQuestions/DeviationFromMeasureSpecification/index.tsx
>    // if there are no labels then there is no need for the additional checkbox
@gitsierra should this be label with the new way the rateLabel file is built

2022-08-24 12:31 UTC, TheDanMiller requested changes
It looks like we are still using the incorrect versions of label / id / mathematicaCategory in various places.

2022-08-24 12:32 UTC, TheDanMiller commented on services/ui-src/src/measures/2022/PQI08AD/validation.ts
> +      return pm?.mathematicaCategory === "Age 65 and older";
Same thing -- I think this is the wrong property now @gitsierra

2022-08-25 14:47 UTC, closed without merging