UI auth
CMSgov/cms-mdct-qmr pull request #348
Opened 2021-12-29 21:58 UTC by abelzer212

Bring out user authentication into its own separate functionality

2022-01-03 05:16 UTC, benjaminpaige commented on services/ui-src/src/components/Layouts/StateLayout/index.tsx
> +        zIndex="1000"
why are we changing this? is there something with a higher index?

2022-01-03 05:45 UTC, benjaminpaige commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +    return !user?.signInUserSession?.idToken?.payload?.["custom:cms_state"];
should we take the result of this and set it into a state variable isReadOnly in the checkAuthState function instead? or maybe doesn't need to be a function at all?

2022-01-03 05:46 UTC, benjaminpaige commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +  }, [isIntegrationBranch]);
should we add Auth to this dependency array?

2022-01-03 05:52 UTC, benjaminpaige commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +      readOnly: isReadOnly(),
im worried 'readOnly' may get lost in the context, how do you feel about isReadOnlyUser?

2022-01-03 05:59 UTC, benjaminpaige commented on services/ui-src/src/measures/2021/FUAAD/index.tsx
> +        />
oh whoa cool, this is an interesting approach, is there suppose to be a semi-transparent background color? id love to see this in action. Also, If this is an approach we do want to go with we could add it into the MeasureWrapper so we only have to add it once.

2022-01-03 06:03 UTC, benjaminpaige commented on services/ui-src/src/components/Layouts/StateLayout/index.tsx
> +        zIndex="1000"
i see why you changed this after reviewing below. how about '10' and change the one below to '9'?

2022-01-03 13:28 UTC, abelzer212 commented on services/ui-src/src/measures/2021/FUAAD/index.tsx
> +        />
The issue with that is that it needs to block everything but not the header and not the footer, so the user can still use the navigations.

2022-01-03 13:31 UTC, abelzer212 commented on services/ui-src/src/components/Layouts/StateLayout/index.tsx
> +        zIndex="1000"
The Z-index is kind of arbitrary, we're just trying to make sure that the clear container is always at the very front of the page, by using 999-1000 we're making sure that any shenanigans that outside packages do to their component CSS will never prioritize what we have. We didn't want to do trial and error on what was the lowest high we could reach

2022-01-03 13:36 UTC, abelzer212 commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +    return !user?.signInUserSession?.idToken?.payload?.["custom:cms_state"];
We had to use the useCallback in this circumstance because we were having issues with re-rendering, and a little more jankness. After a bit of research the internet said this is the way we have to do it.

2022-01-03 13:44 UTC, abelzer212 commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +      readOnly: isReadOnly(),
I feel like readOnly is in the context of the User information, and it's coming from the user provider, so I don't think it's confusing

2022-01-03 13:44 UTC, abelzer212 commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +  }, [isIntegrationBranch]);
We're using Auth to check the current user, what do you mean by that?

2022-01-03 13:58 UTC, abelzer212 commented on services/ui-src/src/measures/2021/FUAAD/index.tsx
> +        />
I moved it to measure wrapper, we didn't put in any color difference, presumably anyone who has admin access will know they aren't allowed to do anything, do you think we should add in like an opaque gray?

2022-01-03 14:23 UTC, abelzer212 commented on services/ui-src/src/measures/2021/FUAAD/index.tsx
> +        />
I made it opaque gray, I think that should be fine. We could also add a sticky note that says "You're not allowed to edit this page" or something like that if anyone gives us feedback that the gray isn't clear enough

2022-01-03 14:55 UTC, 13bfrancis commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +      readOnly: isReadOnly(),
I second what Ben said. How bout something like isAdmin, since this is what the check does in essence. readOnly doesn't make sense because it is not related to the context of the user. readOnly is a behavior that you are implementing, but is not information about the user

2022-01-03 14:58 UTC, daniel-belcher commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +    return !user?.signInUserSession?.idToken?.payload?.["custom:cms_state"];
As additional on this, we have another course, which was to drop the function down to the useMemo call, but if we were to keep it extracted from that we had to make it a callback or it would continuously re-render.

2022-01-03 15:00 UTC, daniel-belcher commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +    return !user?.signInUserSession?.idToken?.payload?.["custom:cms_state"];
I believe the state variable would be an alternative as well, but as it only changes when the user object changes, the useMemo already changes, so just doing assertion there would be the same functionality without an additional hook

2022-01-03 15:02 UTC, 13bfrancis commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +    return !user?.signInUserSession?.idToken?.payload?.["custom:cms_state"];
I'm completely fine with this either way, but I will say from a readability sense that using useState is more readable

2022-01-03 15:03 UTC, daniel-belcher commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +      readOnly: isReadOnly(),
As the check is currently checking for state information, "isStateUser" would be closer to contextual naming, and if a majority is for this, it should be a simple change

2022-01-03 15:04 UTC, 13bfrancis commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +      readOnly: isReadOnly(),
Yeah, sorry. I got it flipped but yeah, something that is directly asserting true or false on what it is checking would be ideal

2022-01-03 15:25 UTC, abelzer212 commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +      readOnly: isReadOnly(),
If it's a quick change I think it's fine to go to isStateUser but I don't think it's important enough to have an in depth argument about it.

2022-01-03 15:45 UTC, benjaminpaige commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +      readOnly: isReadOnly(),
i think isStateUser is the way to go 👍

2022-01-03 15:47 UTC, benjaminpaige commented on services/ui-src/src/measures/2021/FUAAD/index.tsx
> +        />
cool, yeah let's try it out. : )

2022-01-03 15:54 UTC, benjaminpaige commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +    return !user?.signInUserSession?.idToken?.payload?.["custom:cms_state"];
Also just realized this is the state attribute for state users, not the role. we should have both, a check for if the user is a state user, something like: user?.signInUserSession?.idToken?.payload?.["custom:cms_roles"] === "mdctqmr-state-user" 

and also one for the state (region): user?.signInUserSession?.idToken?.payload?.["custom:cms_state"]

2022-01-03 15:54 UTC, benjaminpaige commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +    return !user?.signInUserSession?.idToken?.payload?.["custom:cms_state"];
i hate that these attributes are nested like this, but its what we've got to work with.

2022-01-03 15:57 UTC, daniel-belcher commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +    return !user?.signInUserSession?.idToken?.payload?.["custom:cms_state"];
the state user check is a good point, we can definitely add that to the check

2022-01-04 15:39 UTC, benjaminpaige requested changes
really if you can just add the state attribute to the useUser hook and change readOnly to isStateUser this would be good to go.

2022-01-04 15:39 UTC, benjaminpaige commented on services/ui-src/src/components/MeasureButtons/index.test.tsx
> +  // });
either skip this or fix it or get rid of it

2022-01-04 15:39 UTC, benjaminpaige commented on services/ui-src/src/components/MeasureButtons/index.tsx
> +  const { readOnly } = useUser();
isStateUser

2022-01-04 15:39 UTC, benjaminpaige commented on services/ui-src/src/hooks/authHooks/userProvider.tsx
> +      readOnly: isReadOnly(),
lets change this to isStateUser,
also can we add the state attribute into this useUser as well

2022-01-04 15:39 UTC, benjaminpaige commented on services/ui-src/src/measures/2021/FUAAD/index.tsx
> +          // backgroundColor={"red"}
remove this line

2022-01-04 15:39 UTC, benjaminpaige commented on services/ui-src/src/measures/2021/FUAAD/index.tsx
> +          backgroundImage={"none"}
i thought you had a background color of gray.something here in the stuff i saw, did you get rid of it?

2022-01-04 16:04 UTC, abelzer212 commented on services/ui-src/src/measures/2021/FUAAD/index.tsx
> +          backgroundImage={"none"}
Yeah it's on another branch

2022-01-04 17:44 UTC, benjaminpaige submitted a review, later dismissed

2022-01-04 18:11 UTC, daniel-belcher approved these changes

2022-01-04 19:44 UTC, jdinh8124 approved these changes

2022-01-05 00:30 UTC, merged