[WIP] Oy2-15959: Clear Measure Button
CMSgov/cms-mdct-qmr pull request #509
Opened 2022-02-08 20:04 UTC by jphechter

## Purpose

_Describe the problem or feature in addition to a link to the issues._

#### Linked Issues to Close

_Links to issue(s) that are closed by this PR. Be sure to use the phrase "Closes #XXX" for each issue, so they automatically close_

## Approach

_How does this change address the issue?_

## Learning

_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Assorted Notes/Considerations

_List any other information that you think is important... a post-merge activity, someone to notify, etc._

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-02-10 18:52 UTC, benjaminpaige commented on services/ui-src/src/components/MeasureWrapper/index.tsx
> +      console.log({ errors });
prob dont need these

2022-02-10 18:54 UTC, benjaminpaige commented on services/ui-src/src/components/CompleteMeasureFooter/index.tsx
> +  handleValidation: any;
these should be easy to add types for  - prob just () => void

2022-02-10 18:55 UTC, benjaminpaige commented on services/ui-src/src/components/MeasureWrapper/index.tsx
> +      ></QMR.YesNoModalDialog>
i love that you reached for this, and im not sure whats in the ticket but i dont think we need a modal here. its only used by devs and for e2e testing.

2022-02-10 18:58 UTC, benjaminpaige commented on services/ui-src/src/measures/2021/CPAAD/validation/types.ts
> -    handleValidation?: any;
now i see why you used the any type initially lol

2022-02-10 18:59 UTC, benjaminpaige requested changes
love that you broke these buttons out into their own comp. love that we can use them at the measureWrapper level. great job. just a few small things in the comments. Plus... unit tests: wooot!!

2022-02-11 16:47 UTC, jphechter commented on services/ui-src/src/components/MeasureWrapper/index.tsx
> +      console.log({ errors });
Included.

2022-02-11 16:52 UTC, jphechter commented on services/ui-src/src/components/CompleteMeasureFooter/index.tsx
> +              }}
Included.

2022-02-11 17:08 UTC, jphechter commented on services/ui-src/src/components/MeasureWrapper/index.tsx
> +      ></QMR.YesNoModalDialog>
Included.

2022-02-11 21:46 UTC, benjaminpaige submitted a review, later dismissed
awesome

2022-02-14 17:33 UTC, merged