Cbpad
CMSgov/cms-mdct-qmr pull request #629
Opened 2022-03-07 18:41 UTC by abelzer212

## Purpose

Add CBP-AD measure

#### Linked Issues to Close

https://qmacbis.atlassian.net/browse/OY2-9920

## Approach

I added the capability for the data source component to take an array of sub-options

#### Pull Request Creator Checklist

- [x] This PR has an associated issue or issues.
- [x] The associated issue(s) are linked above.
- [x] This PR meets all acceptance criteria for those issues.
- [x] This PR and linked issue(s) are adequately documented
- [x] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [x] Someone has been assigned this PR.
- [x] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-03-08 19:32 UTC, charmcitygavin requested changes

2022-03-08 19:32 UTC, charmcitygavin commented on services/ui-src/src/measures/2021/CBPAD/validation.ts
> +const IEDValidation = (data: FormData) => {
Looks like the wrong name for the validation, likely from copy/paste

2022-03-08 19:32 UTC, charmcitygavin commented on services/ui-src/src/measures/2021/CBPAD/validation.ts
> +export const validationFunctions = [IEDValidation];
Same as above

2022-03-08 20:17 UTC, jdinh8124 approved these changes

2022-03-08 20:35 UTC, charmcitygavin submitted a review, later dismissed
👍🏻  Looks great, other than the failing Cypress test 😅

2022-03-21 14:00 UTC, gitsierra approved these changes

2022-03-21 14:19 UTC, merged