CHL-AD Measure
CMSgov/cms-mdct-qmr pull request #638
Opened 2022-03-08 17:11 UTC by 13bfrancis

## Purpose

Completing CHL-AD Measure

#### Linked Issues to Close

_Links to issue(s) that are closed by this PR. Be sure to use the phrase "Closes #XXX" for each issue, so they automatically close_

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-03-08 17:57 UTC, jdinh8124 approved these changes

2022-03-08 17:57 UTC, jdinh8124 commented on services/ui-src/src/measures/2021/CHLAD/validation.ts
> +const IEDValidation = (data: FormData) => {
CHLADValidation here

2022-03-08 18:02 UTC, daniel-belcher requested changes

2022-03-08 19:13 UTC, charmcitygavin commented on services/ui-src/src/measures/2021/CHLAD/validation.ts
> +  const age65PlusIndex = 1;
Yep, looks like "Ages 21 to 24" is the only age group in `PMD.qualifiers`.

2022-03-08 19:15 UTC, charmcitygavin requested changes
The only thing I saw were the minor items already mentioned in `validation.ts`. Otherwise, 👍🏻 ✨

2022-03-09 15:47 UTC, jdinh8124 approved these changes

2022-03-15 20:26 UTC, benjaminpaige approved these changes

2022-03-17 01:57 UTC, merged