[WIP] Oy2-9910 Add PCR-AD Measure
CMSgov/cms-mdct-qmr pull request #657
Opened 2022-03-10 15:27 UTC by jphechter

## Purpose

Build and implement the PCR-AD measure.

#### Linked Issues to Close

[Oy2-9910](https://qmacbis.atlassian.net/browse/OY2-9910?atlOrigin=eyJpIjoiMzk0ZTVjNzQxMDVjNGVjNGE5NjMxNzRhODkxMTc4YTAiLCJwIjoiaiJ9)

## Approach

This measure captures NDRs in a completely unique pattern requiring that we build an alternative to the `QMR.Rate` component. This component is referred to as MultiRate in the code (but the name is completely flexible) as it uses different combinations of field values to compute its rates.

The data captured in this component follows the same rules as data captured in the other sections (non-zero denominators, numerator cannot be greater than denominator, etc), and therefore must have unique validations due to the unique data structure.

Things added in addition to new measure files:
- MultiRate component file
- MultiRate tests
- PCR-AD specific validations that check the data structure of the MultiRate component

## Assorted Notes/Considerations

This component has been specifically built for PCR-AD, but it is still data-driven and could be used in another measure with some minimal work. Things like validation functions could be moved into a more globally accessible location.

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-03-14 16:14 UTC, charmcitygavin approved these changes
LGTM! Added some questions for my own curiosity

2022-03-14 16:14 UTC, charmcitygavin commented on services/ui-src/src/utils/form.ts
> +      // If you are thinking about adding another hard-coded value here, consider refactoring this function.
Nice comment/documentation 👍

2022-03-14 18:07 UTC, jphechter commented on services/ui-src/src/components/MultiRate/index.tsx
> +  const ndrForumlas = [
We still calculate NDRs in this component, but the values are generated slightly differently. Each object in `ndrFormulas` is a key to generate a rate. For the first one, the numerator is the 2nd field, the denominator is the first, and the rate is the third.

2022-03-14 18:08 UTC, jphechter commented on services/ui-src/src/components/MultiRate/index.tsx
> +    // Rates need 4 decimal places, but is that included in 16 digits?
I don't know if I did. Probably worth talking to Danny again on this.

This is why I leave myself notes... so others can remind me that I once had an important thought.

2022-03-14 18:42 UTC, jphechter commented on services/ui-src/src/components/MultiRate/index.tsx
> +    // Rates need 4 decimal places, but is that included in 16 digits?
Just talked to Danny. We're good on this. Removing the comment.

2022-03-15 18:39 UTC, abelzer212 commented
![Screen Shot 2022-03-15 at 1 39 03 PM](https://user-images.githubusercontent.com/93547052/158448472-012622dd-6fbc-4b10-bf66-a89849956244.png)
Change readmissinos to readmissions

2022-03-15 18:40 UTC, abelzer212 commented
![Screen Shot 2022-03-15 at 1 40 07 PM](https://user-images.githubusercontent.com/93547052/158448692-4cc87f8c-a672-422a-bba6-f94096fa6bc7.png)
Should appear blank if zero is entered, not NAN

2022-03-15 18:41 UTC, abelzer212 commented
![Screen Shot 2022-03-15 at 1 41 29 PM](https://user-images.githubusercontent.com/93547052/158448830-495bded9-6b32-4b10-8d07-4e31cc0e81eb.png)
Rate shouldn't show up as infinity, it should be blank

2022-03-15 18:42 UTC, abelzer212 commented
No validation appearing at the bottom of the screen if a denominator is entered as zero

2022-03-15 18:43 UTC, abelzer212 commented
![Screen Shot 2022-03-15 at 1 43 30 PM](https://user-images.githubusercontent.com/93547052/158449175-5f5f1296-81d5-4b72-8fed-4f5cb2e80c5f.png)
There's no margin on these three errors and there needs to be

2022-03-15 18:45 UTC, abelzer212 commented
![Screen Shot 2022-03-15 at 1 45 00 PM](https://user-images.githubusercontent.com/93547052/158449422-21038b98-080d-41bb-a30b-a793dce57cc8.png)
Data filled in but OMS section doesn't appear
![Screen Shot 2022-03-15 at 1 45 05 PM](https://user-images.githubusercontent.com/93547052/158449457-8a61600b-3fc4-4c2b-a496-4770f947d90e.png)

2022-03-15 18:46 UTC, abelzer212 commented
I actually can't get the OMS section to show up at all

2022-03-16 15:31 UTC, charmcitygavin requested changes
Other than the minor typo and a [failing test](https://github.com/CMSgov/cms-mdct-qmr/runs/5571980935?check_suite_focus=true) (looks like a string mismatch), looks great! 👍🏻

2022-03-16 16:21 UTC, jphechter commented on services/ui-src/src/components/MultiRate/index.test.tsx
> +  "Count of Expected 30-Day Readmissinos",
Nice catch!

2022-03-16 17:00 UTC, abelzer212 submitted a review, later dismissed

2022-03-16 18:24 UTC, charmcitygavin approved these changes
👍🏻  🎉

2022-03-29 17:00 UTC, abelzer212 submitted a review, later dismissed

2022-03-29 17:01 UTC, abelzer212 approved these changes

2022-03-29 17:18 UTC, merged