[WIP] [Oy2-9953] Add Measure PC01-AD
CMSgov/cms-mdct-qmr pull request #711
Opened 2022-03-22 03:23 UTC by jphechter

## Purpose

Add a new measure PC01-AD.

#### Linked Issues to Close

[Oy2-9953](https://qmacbis.atlassian.net/browse/OY2-9953?atlOrigin=eyJpIjoiYjdjY2MzZjk4Y2JmNGIwMGI1MjY4MTE1MWExZDJhZTAiLCJwIjoiaiJ9)

## Approach

Adds the measure following existing patterns by using flexible, global components.

#### Pull Request Creator Checklist

- [X] This PR has an associated issue or issues.
- [X] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [X] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-03-22 03:25 UTC, jphechter commented on services/ui-src/src/measures/2021/CISCH/data.ts
> +        },
This was added because [this](https://github.com/CMSgov/cms-mdct-qmr/pull/711/files#diff-10eb1b06ba2d6404c55c9dbf97388b3e39e07e9d1f55007bea6c432430d4db6c) was removed

2022-03-22 03:26 UTC, jphechter commented on services/ui-src/src/measures/CommonQuestions/DataSource/index.tsx
> -    }
As far as I can tell CIS-CH was the only measure relying on this and is solved for in it's data.ts file, but it would be good to confirm because this won't throw a merge conflict.

2022-03-22 15:14 UTC, abelzer212 requested changes

2022-03-22 15:59 UTC, jphechter commented on services/ui-src/src/measures/CommonQuestions/DataSource/index.tsx
> -    }
Spoke with James. We're keeping this pattern and will implement across other measures to be the most flexible.

2022-03-22 17:25 UTC, jphechter commented on services/ui-src/src/measures/2021/CISCH/data.ts
> +        },
Added for all measures in master currently that will need these sections added:
- `CBP-AD`
- `CIS-CH`
- `CHL-AD`
- `PPC-AD`

2022-03-22 17:54 UTC, jdinh8124 commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +};
I think this was unique for IET and might not be needed here

2022-03-22 17:54 UTC, jdinh8124 commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +        GV.validateRateZero,
This validation should only run when hybrid is selected as an option. You can refer to CBPAD or CISCH

2022-03-22 17:54 UTC, jdinh8124 commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +    ...GV.validateNoNonZeroNumOrDenom(performanceMeasureArray, OPM, ageGroups),
Hybird measures will need a fourth argument, refer to CBPAD or CISCH or any other hybrid measure in master

2022-03-22 17:54 UTC, jdinh8124 commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +  });
I think this might be unique to IET as well

2022-03-22 18:06 UTC, abelzer212 commented
![Screen Shot 2022-03-22 at 1 05 17 PM](https://user-images.githubusercontent.com/93547052/159546680-5eb51ebe-dee8-426b-89bc-f0e9e41d8376.png)
What is the Medical Records Data Source? (Both can be selected)
Since both can be selected, the third checkbox is un-necessary and should be removed

2022-03-22 18:08 UTC, abelzer212 commented
If Hybrid measure is selected: Manually entered rate should be 0 if numerator is 0, Should not appear as a validation. But it is
![Screen Shot 2022-03-22 at 1 07 43 PM](https://user-images.githubusercontent.com/93547052/159547157-8b8213fe-756f-4b56-ab49-5897764cf4ea.png)
![Screen Shot 2022-03-22 at 1 07 50 PM](https://user-images.githubusercontent.com/93547052/159547169-98564b74-d10b-4c4d-b6b6-dd0540d0eb4b.png)
![Screen Shot 2022-03-22 at 1 07 55 PM](https://user-images.githubusercontent.com/93547052/159547179-1f21541e-db77-41d5-b34b-69236a76590f.png)

2022-03-22 18:13 UTC, abelzer212 commented on services/ui-src/src/measures/2021/PC01AD/data.ts
> +              value: "Both (EHR and Paper)",
This third option isn't necessary, look at CBP-AD for reference

2022-03-22 18:15 UTC, abelzer212 requested changes
Need to respond to all of my comments. Let me know if you have any questions on any of them.

2022-03-22 18:21 UTC, jphechter commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +const IEDValidation = (data: FormData) => {
Welp. You definitely know where I copied this from lol

2022-03-24 15:01 UTC, jdinh8124 commented on services/ui-src/src/measures/2021/CHLAD/data.ts
> +        },
I believe CHLAD doesn't need this

2022-03-24 19:41 UTC, jdinh8124 commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +  if (data["DidReport"] === "no") {
const whyNotReporting = data[DC.WHY_ARE_YOU_NOT_REPORTING];
  const OPM = data[DC.OPM_RATES];
  const dateRange = data[DC.DATE_RANGE];
  const didCalculationsDeviate = data[DC.DID_CALCS_DEVIATE] === DC.YES;

  const DefinitionOfDenominator = data[DC.DEFINITION_OF_DENOMINATOR];
  if (data[DC.DID_REPORT] === DC.NO) {

Soft recommendations to use data constants

2022-03-24 19:42 UTC, jdinh8124 approved these changes

2022-03-24 19:42 UTC, jdinh8124 commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +} from "measures/globalValidations/omsValidationsLib";
Soft recommendation to import 
import * as GV from "measures/globalValidations";

2022-03-24 19:53 UTC, jphechter commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +  if (data["DidReport"] === "no") {
Good callout. I pulled this from CBP-AD. Updating in both.

2022-03-24 19:53 UTC, jphechter commented on services/ui-src/src/measures/2021/PC01AD/validation.ts
> +} from "measures/globalValidations/omsValidationsLib";
Same here. Great callout.

2022-03-25 13:35 UTC, abelzer212 commented
![Screen Shot 2022-03-25 at 8 34 30 AM](https://user-images.githubusercontent.com/93547052/160130762-8afa50c5-fde1-4194-b142-eb5a31dae6b1.png)
![Screen Shot 2022-03-25 at 8 34 17 AM](https://user-images.githubusercontent.com/93547052/160130765-4c79744e-1727-4366-a715-dfa4339e0a61.png)
There should be only one Description for all data sources at the bottom of Data Source. Compare to IET-AD to see this implementation

2022-03-25 13:36 UTC, abelzer212 commented
![Screen Shot 2022-03-25 at 8 36 07 AM](https://user-images.githubusercontent.com/93547052/160130959-b27071d9-7175-4cbe-8479-2932556dfc1f.png)
This is how it should look

2022-03-25 17:14 UTC, jphechter commented
@abelzer212 noted the DataSource discrepancy between Figma and intended design in [Oy2-9953](https://qmacbis.atlassian.net/browse/OY2-9953?atlOrigin=eyJpIjoiYjdjY2MzZjk4Y2JmNGIwMGI1MjY4MTE1MWExZDJhZTAiLCJwIjoiaiJ9)

Reverted changes made to `DataSource` component. This section now appears the same as other measures.

2022-03-25 18:10 UTC, abelzer212 submitted a review, later dismissed

2022-03-29 18:15 UTC, abelzer212 approved these changes

2022-03-30 12:37 UTC, jphechter commented
Seeing consistent inconsistent test behavior across all branches. `oy2_9963_CPC_CH.spec.js` is failing on this branch, but it's due to a race condition in the test. Added a `cy.wait(1000)` to one of the setup steps and that fixed the issue locally. I'm hesitant to push that up because it will affect all the other tests and I think it's worth discussing as a team first.

2022-03-30 21:05 UTC, benjaminpaige approved these changes

2022-03-30 21:06 UTC, merged