oy2 9916 wcv-ch
CMSgov/cms-mdct-qmr pull request #762
Opened 2022-03-29 18:44 UTC by daniel-belcher

added new measure

[ticket](https://qmacbis.atlassian.net/browse/OY2-9916?atlOrigin=eyJpIjoiYjljZjdkYmJmMGRjNGQ4MzhiN2M5YWFlNTlkMmZmYTEiLCJwIjoiaiJ9)

[instance](https://d1pf4rui5az5r9.cloudfront.net/)

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-03-29 18:48 UTC, abelzer212 requested changes

2022-03-29 18:48 UTC, abelzer212 commented on services/ui-src/src/measures/2021/WCVCH/data.ts
> +export const dataSourceData: DataDrivenTypes.DataSource = {
This is the default data source so you don't need to include this in the data - Lines 21-47

2022-03-29 19:00 UTC, abelzer212 commented
![Screen Shot 2022-03-29 at 1 59 18 PM](https://user-images.githubusercontent.com/93547052/160685330-6b6d4ac0-3d18-477e-8752-84442074d95b.png)
![Screen Shot 2022-03-29 at 1 59 10 PM](https://user-images.githubusercontent.com/93547052/160685335-fa92eff6-28c4-4621-b6b8-360ae9f701a6.png)
Missing Validation: Ensure that “Total” NDR set is auto calculated from the according age ranges.
The calculated total rate should be 50, I manually entered 66 and it's not throwing an error

2022-03-31 18:29 UTC, jphechter commented on services/ui-src/src/measures/2021/WCVCH/validation.ts
> +      ],
Do you need this one?
```suggestion
      GV.validateRateZero,
      ],
```

2022-03-31 18:30 UTC, jphechter commented on services/ui-src/src/measures/2021/WCVCH/validation.ts
> +  ];
```suggestion
  GV.validateRateZero
  ];
```

Same question

2022-04-11 17:22 UTC, closed without merging