[Oy2-8982] Create AMB-CH Measure
CMSgov/cms-mdct-qmr pull request #774
Opened 2022-03-31 19:08 UTC by jphechter

## Purpose

Create the AMB-CH measure using commonly used question components.

#### Linked Issues to Close

[Oy2-8982](https://qmacbis.atlassian.net/browse/OY2-8982?atlOrigin=eyJpIjoiNTY4YzhlN2U4NGUxNDk2ZmJhZTFiMjI4MDgyMDNiZDUiLCJwIjoiaiJ9)

#### Pull Request Creator Checklist

- [X] This PR has an associated issue or issues.
- [X] The associated issue(s) are linked above.
- [X] This PR meets all acceptance criteria for those issues.
- [X] This PR and linked issue(s) are adequately documented
- [X] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [X] Someone has been assigned this PR.
- [X] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-04-01 13:20 UTC, abelzer212 commented
You probably shouldn't create your own version of the definition of population question. Rather I'd add some functionality in the existing question to address what you're adding, which seems to be a watch on the total which can be shown with your "watch" and with an optional flag that's passed in from the AMB measure to show it.

2022-04-01 13:24 UTC, abelzer212 requested changes

2022-04-01 13:24 UTC, abelzer212 commented on services/ui-src/src/measures/2021/AMBCH/questions/DefinitionsOfPopulation/index.tsx
> +                    label="What percent of your measure-eligible Managed Care Organization/Pre-paid Inpatient Health Plan (MCO/PIHP) population are included in the measure?"
This text doesn't need to be different, it should match the other measures. James removed several things from this component per conversations with Marc and Karen, I would reach out to him to understand why these are gone and why you don't need to add them back

2022-04-01 13:27 UTC, abelzer212 commented
![Screen Shot 2022-04-01 at 8 25 55 AM](https://user-images.githubusercontent.com/93547052/161272704-b8f35111-b931-41ce-a10b-ac2291ac1a24.png)
Rate is times 1000 but I can only manually enter 2 digits for the rate field. I should be able to enter 0-1000, but I can only enter 0-99

2022-04-01 13:29 UTC, abelzer212 commented
![Screen Shot 2022-04-01 at 8 28 40 AM](https://user-images.githubusercontent.com/93547052/161273082-1b510dde-bb61-4856-aad1-d115c65a296c.png)
![Screen Shot 2022-04-01 at 8 28 34 AM](https://user-images.githubusercontent.com/93547052/161273083-2eb2ea91-7bb8-4d6e-809b-6a40491a1d49.png)
I used the auto-calculations for all of the NDR Sets but I'm still getting the Total Rate error. 
This is probably a rounding issue, or we need to give this check some wiggle room. Probably + or - 1 but I'd talk with Marc and Karen on what they want

2022-04-05 13:50 UTC, jphechter commented
I was unable to reproduce the validation error. Tried with the same inputs and it's all working now. It could be in part due to work Daniel had done on WCC-CH for the totaling portion of Rate.

2022-04-05 13:57 UTC, abelzer212 commented
![Screen Shot 2022-04-05 at 8 57 22 AM](https://user-images.githubusercontent.com/93547052/161770471-bda7360b-6989-4c67-acea-f9a9b76f01e4.png)
![Screen Shot 2022-04-05 at 8 57 16 AM](https://user-images.githubusercontent.com/93547052/161770472-ee7fd30a-c477-43af-8af6-8b88a03ddac7.png)
It looks like now it's not triggering at all

2022-04-05 13:58 UTC, abelzer212 commented
The total Rate mismatch validation is also failing to trigger in OMS.

2022-04-07 15:37 UTC, abelzer212 approved these changes

2022-04-11 15:38 UTC, closed without merging