[Oy2-8944] Create Measure 11: CCP-CH
CMSgov/cms-mdct-qmr pull request #785
Opened 2022-04-04 14:32 UTC by jphechter

## Purpose

Create CCP-CH using common question components.

#### Linked Issues to Close

[Oy2-8944](https://qmacbis.atlassian.net/browse/OY2-8944?atlOrigin=eyJpIjoiNjk3MDE4MWE5NDZkNDUwOGJjYzljNmZlZGIwNjM0MWYiLCJwIjoiaiJ9)

## Approach

Used common question components and established build patterns to create this measure.

#### Pull Request Creator Checklist

- [X] This PR has an associated issue or issues.
- [X] The associated issue(s) are linked above.
- [X] This PR meets all acceptance criteria for those issues.
- [X] This PR and linked issue(s) are adequately documented
- [X] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [X] Someone has been assigned this PR.
- [X] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-04-04 15:03 UTC, abelzer212 commented
<img width="314" alt="Screen Shot 2022-04-04 at 10 00 01 AM" src="https://user-images.githubusercontent.com/93547052/161572856-ecfb8e31-882f-440a-b009-f63f767d71c6.png">
![Screen Shot 2022-04-04 at 9 59 48 AM](https://user-images.githubusercontent.com/93547052/161572863-f04d55c6-2fab-4dbd-8d19-0b52e6bb62c1.png)
![Screen Shot 2022-04-04 at 9 59 35 AM](https://user-images.githubusercontent.com/93547052/161572864-4f7412a2-1f36-4b64-84f6-028d412bbf20.png)

Missing a few Validations:
1. The Three day Postpartum Rate must be smaller than the 60 day Postpartum rate within EACH category
2. The Three Days Postpartum Rate for Most Effective or moderately effective must be BIGGER than the Three Days postpartum Rate for Long-acting reversible Method of Contraception
3. The same as above but for Sixty days
4. All 3 of the above must also be applied in OMS

2022-04-04 15:19 UTC, abelzer212 requested changes

2022-04-04 15:19 UTC, abelzer212 commented on services/ui-src/src/measures/2021/CCPCH/validation.ts
> +
Here for the performance measure

2022-04-04 20:29 UTC, jphechter commented on services/ui-src/src/measures/2021/CCPCH/validation.ts
> +        GV.validateRateZero,
Included.

2022-04-04 20:29 UTC, jphechter commented on services/ui-src/src/measures/2021/CCPCH/validation.ts
> +
Included.

2022-04-06 13:47 UTC, charmcitygavin approved these changes

2022-04-08 14:07 UTC, abelzer212 submitted a review, later dismissed

2022-04-08 14:38 UTC, merged