Add SFMCH Measure
CMSgov/cms-mdct-qmr pull request #788
Opened 2022-04-04 18:13 UTC by gitsierra

## Purpose

https://qmacbis.atlassian.net/browse/OY2-9936

Application endpoint:  https://d1go2zrn4qqa8k.cloudfront.net/

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-04-04 18:33 UTC, abelzer212 requested changes

2022-04-04 18:33 UTC, abelzer212 commented on services/ui-src/src/measures/2021/SFMCH/validation.ts
> +const validate7DaysGreaterThan30Days = (data: FormData) => {
un-necessary

2022-04-04 18:33 UTC, abelzer212 commented on services/ui-src/src/measures/2021/SFMCH/validation.ts
> +    ...validate7DaysGreaterThan30Days(data),
un-necessary

2022-04-04 18:33 UTC, abelzer212 commented on services/ui-src/src/measures/2021/SFMCH/validation.ts
> +
You're missing a validation that makes sure that "at least one molar filled rate is less than all four molar's filled"
It will behave similarly to the 7 day check you have in here though. 

It will also need to work for OMS

2022-04-06 14:40 UTC, benjaminpaige commented on services/ui-src/src/measures/2021/SFMCH/index.tsx
> +          <CMQ.DefinitionOfPopulation childMeasure={true} />
super small, but you can just do:
`<CMQ.DefinitionOfPopulation childMeasure />`

2022-04-06 14:41 UTC, benjaminpaige reviewed
just some small suggestions

2022-04-11 17:47 UTC, benjaminpaige approved these changes

2022-04-11 17:50 UTC, abelzer212 approved these changes

2022-04-11 18:07 UTC, merged