Add Data Source Validation
CMSgov/cms-mdct-qmr pull request #856
Opened 2022-04-12 16:38 UTC by gitsierra

## Purpose

https://qmacbis.atlassian.net/browse/OY2-17347

Endpoint: TBD

#### Pull Request Creator Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.
- [ ] Someone has been assigned this PR.
- [ ] At least one person has been marked as reviewer on this PR.

#### Pull Request Reviewer/Assignee Checklist

- [ ] This PR has an associated issue or issues.
- [ ] The associated issue(s) are linked above.
- [ ] This PR meets all acceptance criteria for those issues.
- [ ] This PR and linked issue(s) are adequately documented
- [ ] This PR and linked issues(s) are a complete description of the changeset; an individual or team should be able to understand the issue(s) and changes by reading through this PR and it's links, with no further interaction.

2022-04-14 13:57 UTC, abelzer212 commented
It looks good, it looks like you missed the last batch of measures that went in yesterday though: AMB, WCC, and 3 others.

2022-04-14 17:34 UTC, abelzer212 submitted a review, later dismissed

2022-04-14 18:29 UTC, jphechter requested changes
Would really like to see the tests blown out a little more. Feel free to hit me up.

2022-04-14 18:29 UTC, jphechter commented on services/ui-src/src/measures/globalValidations/tests/validateOneDataSource.test.ts
> +
Can we add a couple other test cases in here as well? Ideally any set of tests should be covering both the expected negative results and positive.

- test for when data source is complete. This should be the default state of the data in `testFormData` and if it's not we should update that seed data to match that state.
- other expected data failures (if DATA_SOURCE.length is 0 but source DATA_SOURCE_SELECTIONS is not, etc)

2022-04-14 18:29 UTC, jphechter commented on services/ui-src/src/measures/globalValidations/validationsLib.tsx
> +  }
Considering all of our data source strings are constants in `dataConstants.ts`, could we add an interface that further validates what strings we're checking against here? Possibly out of scope for this work, but I think it would be a really cool feature.

2022-04-14 18:31 UTC, jphechter commented on services/ui-src/src/measures/globalValidations/tests/validateOneDataSource.test.ts
> +
It could be argued overkill, but the second bullet is addressing what I tried to do in `ensureBothDatesCompletedInRange.test.tsx`. The check isn't just that data is present, but that the shape of the data is as expected.

2022-04-15 12:06 UTC, jphechter commented on services/ui-src/src/measures/globalValidations/validationsLib.tsx
> +  if (!data.DataSource || data.DataSource.length === 0) {
@gitsierra @abelzer212 This is more a point of clarification that I didn't consider yesterday. Are we only concerned about the checkboxes in red, or do we also need to validate a selection for the checkboxes in blue? Right now, this function is only concerned about the existence of a top level selection.

I know in the case of EHR or Other we then prompt for a description. Should the user be required to provide a description for one of those selections? This is a pattern we follow in other sections of the measure.

If we don't need to worry about these checks, then this is good to go.

![Screen Shot 2022-04-15 at 7 59 20 AM](https://user-images.githubusercontent.com/22647707/163568426-9c8543fa-32d6-4382-8d84-476a10a166b0.png)

2022-04-20 17:44 UTC, merged